spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm550858
    password: 211002
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
